import Link from "next/link";
import { FileIcon, StarIcon } from "lucide-react";

import { Button } from "@/components/ui/button";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="container mx-auto pt-12">
      <div className="flex gap-8">
        <div className="w-40 flex flex-col gap-4">
          <Button asChild variant="link">
            <Link href="/dashboard/files" className="flex gap-2">
              <FileIcon /> All Files
            </Link>
          </Button>

          <Button asChild variant="link">
            <Link href="/dashboard/favorites" className="flex gap-2">
              <StarIcon /> Favorites
            </Link>
          </Button>
        </div>

        <div className="flex-grow">{children}</div>
      </div>
    </main>
  );
}
